# Adds IntelliSense/validation in VS Code
"$schema" = "node_modules/wrangler/config-schema.json"

name = "furrytails"
compatibility_date = "2026-05-10"

# Observability (New default recommendation)
[observability]
enabled = true

# Static assets
[assets]
directory = "./dist"
